### PR TITLE
new product images

### PR DESCRIPTION
**Pull request by julianjocham**

### CODE REVIEW

**Comment by ghost** [comment]
A new product import is necessary, because the column headings for the flavor in the `products_without_arrays.csv` file were not correct.
As a consequence, the values of the flavor for the products are currently missing.

**Review by ghost — CHANGES_REQUESTED** [review]
A new product import has to be done.

**Review by julianjocham — COMMENTED** [review]
import will be done

**Comment by julianjocham** [comment]
imported, merging is blocked

**Review by ghost — APPROVED** [review]

**Pull request merged**
